## Python and Numpy - Vectorization

Numpy is a library that allows for linear algebra functions to take place to perform operations on data

<a name="toc_40015_3"></a>
# Vectors
<a name="toc_40015_3.1"></a>
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >Vectors are ordered arrays of numbers. The elements of a vector are all the same type and cannot contain e.g. letters and numbers. The number of elements in the array is often referred to as the *DIMENSION/RANK*. The vector shown has a dimension of $n$. The elements of a vector can be referenced with an index. In math settings, indexes typically run from 1 to n. In computer science indexing will typically run from 0 to n-1. 


<a name="toc_40015_3.2"></a>
## NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`) where dimension/rank refers to number of indexes of an array Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array.

 - 1-D array, shape (n,): n elements indexed [0] through [n-1]
 

In [1]:
import numpy as np 

In [22]:
a = np.zeros(4)
print(f"a = {a} , shape of a = {np.shape(a)} , data type of a = {a.dtype}")

a = np.zeros(4, );
print(f"a = {a} , shape of a = {np.shape(a)} , data type of a = {a.dtype}")

a = np.random.random_sample(4)
print(f"a = {a} , shape of a = {np.shape(a)} , data type of a = {a.dtype}")

a = np.random.rand(4)
print(f"a = {a} , shape of a = {np.shape(a)} , data type of a = {a.dtype}")

a = [0. 0. 0. 0.] , shape of a = (4,) , data type of a = float64
a = [0. 0. 0. 0.] , shape of a = (4,) , data type of a = float64
a = [0.38734211 0.69080907 0.91760618 0.32693792] , shape of a = (4,) , data type of a = float64
a = [0.68872246 0.22677998 0.77035445 0.58627003] , shape of a = (4,) , data type of a = float64


some functions do not actually shape a tuple:

In [21]:
a = np.arange(4, 10, 2) # start , stop, step
print(a)

a = np.arange(4,)
print(a)

[4 6 8]
[0 1 2 3]


# Operations on Vectors

## Indexing:

In [32]:
a = np.arange(10)
print(a)

print(a[2].shape)
print(a[2]) # Accessing a element returns a scalar

print(a[-1])

try :
    c = a[10]
    print(c)
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
()
2
9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


## Slicing:

In [44]:
a = np.arange(10)
print(f"a             {a}")
#access 5 consecutive elements (start:stop:step)

c = a[2:7:1]
print(f"a[2:7:1] =    {c}")

# access 3 elements separated by two 
c = a[2:7:2]
print(f"a[2:7:1] =    {c}")

# access all elements index 3 and above
c = a[3:]
print(f"a[3:] =       {c}")

# access all elements up to index 3 (inclusive)
c = a[:3]
print(f"a[:3] =       {c}")

# access all elements
c = a[:]
print(f"a[:] =       {c}")

a             [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =    [2 3 4 5 6]
a[2:7:1] =    [2 4 6]
a[3:] =       [3 4 5 6 7 8 9]
a[:3] =       [0 1 2]
a[:] =       [0 1 2 3 4 5 6 7 8 9]


# Single Vector Operations

In [53]:
a = np.array([1, 2, 3, 4])
print(f"a =             {a}")

# negate elements of a
b = -a
print(f"b = -a :        {b}")

# sum all elements of a, returns scalar (single value)
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a) : {b}")

b = a**2
print(f"b = a**2       : {b}")

a =             [1 2 3 4]
b = -a :        [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a) : 2.5
b = a**2       : [ 1  4  9 16]


## Vector with element wise operations
-> Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

In [59]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
print(a + b)

c = np.array([1, 2])
try:
    d = a + c # c is incompatible with a and b due to different sizes
except Exception as e:
    print("The error message is:", e)

[0 0 6 8]
The error message is: operands could not be broadcast together with shapes (4,) (2,) 


In [60]:
a = np.array([1, 2, 3, 4])
b = 5 * a
print(b)

[ 5 10 15 20]
